#!/bin/bash
#chkconfig: 2345 95 20
   # description: sassdoc for tv & iplayer
   # processname: sassdoc

NAME="Sassdoc"
NODE_BIN_DIR=/usr/bin/
NODE_PATH=/root/node_modules
APPLICATION_DIRECTORY=/root/tviplayer-sassdoc/sassdoc
APPLICATION_START=app.js
PIDFILE=/var/run/sassdoc.pid
LOGFILE=/var/log/sassdoc.log
 
# Add node to the path for situations in which the environment is passed.
PATH=$NODE_BIN_DIR:$PATH
# Export all environment variables that must be visible for the Node.js
# application process forked by Forever. It will not see any of the other
# variables defined in this script.
export NODE_PATH=$NODE_PATH
 
start() {
    echo "Starting $NAME"
    forever --pidFile $PIDFILE --sourceDir $APPLICATION_DIRECTORY \
        -a -l $LOGFILE --minUptime 5000 --spinSleepTime 2000 \
        start $APPLICATION_START /mnt/hgfs/workspace/tviplayer/webapp/static-versioned/sassdoc.json
    RETVAL=$?
}
 
stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
        forever --sourceDir $APPLICATION_DIRECTORY \
            stop $APPLICATION_START
        rm -f $PIDFILE
        RETVAL=$?
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}
 
restart() {
    echo "Restarting $NAME"
    stop
    start
}
 
status() {
    echo "Status for $NAME:"
    RETVAL=$?
}
 
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
